# Generated by Django 5.1.6 on 2025-02-26 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[(' en attente', 'en attente'), ('acceptee', 'Acceptée'), ('rejete', 'Rejetée')], default=' en attente', max_length=20),
        ),
    ]
